python Mancala.py &
python Mancala.py &
python Mancala.py &
python Mancala.py &
python Mancala.py &
python Mancala.py &
python Mancala.py &
python Mancala.py &
python Mancala.py &
python Mancala.py &
